# What single frames of the vanilla UFO sets show. The painter only sees 32x40 pixels and cannot
# tell wheat from an orange texture or a hay bale from a crate; these words go into the prompt
# (before the set's short context). "a-b: text" ranges are expanded by hints_for(). A hints.json
# next to a set's sheets adds to or overrides these.
#
# Written by looking at the sheets (extract_pck.py output); descriptions are short and concrete.

HINTS = {
    "CULTIVAT.PCK": {
        0: "green grass lawn", 1: "bare dirt patch with grass edges", 2: "dry sandy soil",
        3: "ploughed field, red-brown soil furrows", 4: "ripe golden wheat field, dense tall stalks",
        5: "meadow grass with small wildflowers", 6: "young green sprouts in rows on dirt", 7: "grey boulder on grass",
        8: "vegetable crops, green plants in rows on dirt", 9: "apple tree with dark green leaves and red apples",
        10: "dark tilled soil", 11: "dead dry crops, withered brown stalks", 12: "leafy green tree",
        13: "dead bare tree, grey branches", "14-15": "old stone wall", "16-19": "trimmed green hedge",
        20: "stone gate pillar", 21: "trimmed green hedge", 22: "green bush", "23-24": "wooden rail fence",
        "25-26": "broken wood debris on the ground", "27-28": "wooden rail fence",
        "29-30": "broken wood debris on the ground", "31-32": "wooden rail fence, broken",
        "33-34": "hedge, damaged", 35: "dirt and debris", 36: "hedge, damaged",
    },
    "BARN.PCK": {
        "0-1": "wooden plank floor", 2: "corrugated grey metal roof", "3-4": "hay bale, straw block",
        "5-6": "wooden plank barn wall", "7-8": "wooden plank barn wall with a small window", 9: "wooden wall post",
        "10-11": "yellow sandstone brick wall", "12-13": "yellow brick wall with a window opening", 14: "yellow brick wall post",
        15: "wooden staircase", 16: "wooden staircase, upper flight with railing", "17-18": "dark wooden barn door",
        19: "pink stone floor tiles", 20: "dark slate roof panel", "21-22": "broken wooden fence rails",
        "23-24": "rubble of yellow bricks", "25-26": "broken dark wood debris", 27: "dark grey rubble ground",
        28: "burnt dark brown ground",
    },
    "ROADS.PCK": {
        0: "grey gravel road surface", "1-8": "grey gravel road surface with a concrete kerb edge",
        9: "dark asphalt road", "10-12": "dark asphalt road with a white lane line", 13: "cracked dark asphalt",
        14: "dark brown crater, burnt ground", 15: "grey steel lamp post pole", 16: "street lamp head with two orange lights",
        17: "broken lamp post base", 18: "red mail box", 19: "metal litter bin", 20: "black fire hydrant",
        21: "glass telephone booth with a white frame", 22: "wrecked telephone booth, bent frame",
    },
    "FRNITURE.PCK": {
        0: "wooden table", 1: "small wooden table with a vase of flowers", "2-3": "wooden chair",
        4: "wooden cabinet with a blue table lamp", 5: "wooden cabinet with a television set", 6: "wooden bookshelf full of books",
        7: "broken wooden furniture debris", 8: "dark red armchair", 9: "blue armchair", 10: "floor lamp with a beige shade",
        11: "broken dark red armchair debris", 12: "broken blue armchair debris", 13: "blue kitchen sink cabinet with a tap",
        14: "broken blue sink debris", 15: "blue kitchen counter with dishes", 16: "blue kitchen counter with bottles",
        17: "white electric stove with four burners", 18: "white microwave oven", 19: "white refrigerator",
        20: "broken white appliance debris", 21: "wooden bed with a red blanket, head end", 22: "wooden bed with a red blanket, foot end",
        23: "tall wooden wardrobe", 24: "small wooden nightstand", 25: "broken wooden debris",
    },
    "FOREST.PCK": {
        0: "green grass", "1-2": "grass with brown pine needles and twigs", 3: "dark green moss patch",
        4: "tall green grass", 5: "tall green grass tuft", 6: "grass with a dark green shrub", 7: "grass with grey pebbles",
        8: "small dead sapling on grass", 9: "large tree stump with roots on grass", 10: "tree trunk base with roots and red flowers",
        11: "fallen tree stump with green ferns", 12: "fallen log", 13: "fallen log with branches", 14: "hollow fallen log",
        15: "dead dry branches on the ground", 16: "small pine sapling", 17: "dry red-brown shrub", 18: "small green bush",
        19: "wide green bush", 20: "green bush with red berries", 21: "tall thin pine tree with sparse branches",
        22: "dark green pine tree", 23: "dense pine tree canopy", "24-26": "dense conifer foliage, dark green needles",
        "27-39": "grassy hill slope with a sandy earth side", 40: "grassy block with tall sandy cliff sides",
        41: "grassy block with low sandy sides", "42-47": "dense pine tree canopy, dark green needles",
        "48-51": "pine tree canopy with a brown branch", "52-56": "dense pine tree canopy, dark green needles",
        57: "pine tree trunk with branches", 58: "burnt black tree stump",
    },
    "JUNGLE.PCK": {
        0: "green grass", 1: "tall jungle grass", 2: "small dark green bush on grass",
        "3-4": "dense jungle bush with vines and branches", 5: "leafy jungle tree", 6: "tall jungle tree with a thick trunk",
        7: "leafy jungle tree with spreading branches", 8: "fern with blue flowers", 9: "low plant with blue flowers on grass",
        10: "fern with blue flowers", 11: "broad-leaf tropical plant", 12: "spiky agave plant", 13: "tall banana leaves",
        14: "banana plant", 15: "low green plant on grass", 16: "broad-leaf banana plant", 17: "palm tree",
        18: "coconut palm tree", "19-22": "large tropical leaves on grass", 23: "jungle floor with a red flower and vines",
        "24-27": "red tropical flowers on grass", "28-31": "blue tropical flowers on grass", 32: "palm trunk base on grass",
        33: "palm tree trunk section", "34-42": "palm fronds and jungle fern leaves", "43-46": "green grass",
        47: "broken plants and branches", 48: "small palm tree", 49: "grass with green shoots", 50: "shredded plants with broken branches",
        51: "broken pale branches with leaves", "52-55": "dark green mossy jungle ground", 56: "dead dry branches on grass",
        57: "dead bare tree", 58: "small palm tree", 59: "dead pale dry bush", "60-61": "dead dark tree with bare branches",
        "62-65": "jungle ground with fallen branches and logs", "66-79": "dense jungle tree canopy, green leaves",
        "80-81": "large jungle tree trunk with roots on grass",
    },
    "DESERT.PCK": {
        0: "yellow desert sand", 1: "desert sand with a skull", 2: "desert sand with a dark burrow hole",
        3: "desert sand with an animal skull", "4-5": "desert sand with a snake", 6: "desert sand with bones",
        7: "desert sand with a small cactus", 8: "desert sand with a dry dead grass patch", 9: "desert sand with a coiled snake",
        10: "round barrel cactus", 11: "small dry shrub with red berries", 12: "tall saguaro cactus with yellow flowers",
        13: "dead cactus stump with small plants", 14: "prickly pear cactus with red fruits", 15: "broken cactus pieces on sand",
        16: "dead dry tree with a bent trunk", 17: "dead grey tree", 18: "burnt dead stump on sand",
        "19-21": "desert sand with a dark burnt patch", "22-23": "grey boulder on sand", "24-26": "broken grey rocks and pebbles on sand",
        "27-39": "sand dune slope", 40: "tall sand block", 41: "low sand block",
    },
    "MOUNT.PCK": {
        0: "pale pink-grey gravel", 1: "gravel with orange pebbles", "2-4": "gravel with dark grey rocks",
        "5-6": "gravel with green grass tufts", 7: "brownish gravel", 8: "grey scree with a dark stone",
        "9-14": "pale grey rocky ground with dark cracks", "15-16": "dead tree with bare brown branches on rocky ground",
        "17-23": "grey gravel with brown dirt patches", 24: "large white boulder with a dark cave opening",
        25: "white rock pillar", 26: "large white boulder", "27-28": "pale grey rock slope", "29-39": "grey rocky hillside slope",
        "40-44": "grey rock cliff block with cracks", "45-46": "white snow-covered boulder", 47: "dead red-brown tree trunk",
        "48-49": "fallen dark brown log", 50: "brown tree stump on gravel", "51-52": "broken dark brown log",
        53: "pinkish rocky ground with a dark patch",
    },
    "POLAR.PCK": {
        0: "snow with a dark blue ice hole", "1-6": "snow with a brown mud patch", "7-10": "snow with a broken blue ice slab",
        11: "snow with an ice block", 12: "snow with ice shards", "13-18": "snow with blue ice patches and cracks",
        "19-31": "snow slope with a dark blue ice side", 32: "white snow", "33-39": "snow with grey ice lumps",
        "40-47": "wind-blown snow drift", "48-59": "snow with a dark crevasse crack", 60: "small dark rock on snow",
        "61-62": "small blue ice fragment", "63-71": "dark blue sea ice with a snow edge", "72-75": "dark blue sea ice with snow lumps",
        76: "dark blue sea ice", "77-80": "dark blue sea ice with a snow edge", "81-83": "sea ice with a snow mound",
        "84-87": "dark blue sea ice with a snow edge", "88-90": "sea ice with a snow mound", 91: "dark blue sea ice",
        "92-102": "dark blue sea ice with a snow edge", "103-105": "sea ice with a snow mound",
        "106-110": "dark blue sea ice with a snow edge", "111-113": "sea ice with a snow mound",
        "114-119": "dark blue sea ice with a snow edge", 120: "sea ice with a snow mound", "121-122": "dark blue sea ice with a snow edge",
    },
    "URBAN.PCK": {
        "0-1": "grey brick wall", "2-3": "grey brick wall with a window and yellow curtains", 4: "grey brick wall post",
        "5-6": "grey brick rubble", "7-8": "worn white plaster wall with vertical panels", "9-10": "white wall with a window",
        11: "white wall post", "12-13": "white wall rubble", "14-15": "yellow plaster wall with an open doorway",
        "16-17": "yellow plaster wall with a window", "18-19": "plain yellow plaster wall", 20: "yellow wall post",
        21: "brown wooden staircase", 22: "brown wooden staircase, upper flight", "23-24": "broken wooden beam debris",
        25: "brown wooden plank floor", 26: "burnt wooden floor with a hole", "27-28": "white panel door",
        "29-30": "blue door with a brass handle", 31: "white panelled wall", 32: "beige panel wall",
        "33-34": "beige wall with a small window", "35-36": "beige wall with a vertical vent strip", 37: "beige wall post",
        "38-39": "beige wall rubble", 40: "grey concrete floor", 41: "grey concrete floor with dust and rubble",
        "42-43": "stacked yellow cardboard boxes with labels", "44-46": "yellow cardboard box with a label", 47: "broken cardboard box debris",
        48: "grey concrete staircase", 49: "grey concrete staircase, upper flight", "50-51": "burnt rubble pile",
        52: "grey corrugated metal floor", 53: "dark grey rubble", 54: "grey concrete pillar", "55-56": "grey concrete staircase",
        "57-58": "burnt rubble pile", "59-60": "green corrugated metal fence", 61: "short green metal fence", 62: "green fence rail",
        63: "broken green metal fence", "64-65": "green corrugated metal fence", 66: "short green metal fence", 67: "green fence rail",
        68: "broken green metal fence", "69-70": "plain light grey wall", "71-72": "white wall with a large window", 73: "white wall post",
        "74-75": "white wall rubble", 76: "white concrete pillar", 77: "broken pillar debris", 78: "beige linoleum floor",
        79: "beige floor with a dark burnt patch", 80: "white tiled floor", "81-82": "white tiled floor with rubble",
        "83-84": "glass shop door with a sign", 85: "white vending machine with a green screen", 86: "black rubber tyre", 87: "red watering can",
        88: "yellow shop counter with a grey top", 89: "yellow shop counter with a cash register", 90: "yellow shop counter with a grey top",
        "91-92": "broken wooden counter debris", 93: "metal shelf rack with blue and red cans", 94: "metal shelf rack with green bottles and crates",
        95: "metal shelf with green cans and a beach ball", 96: "blue crate of cans", 97: "tray of brown bottles", 98: "green crate of cans",
        99: "purple crate", 100: "green metal barrel", 101: "shop display bin of potatoes with a price sign",
        "102-103": "shop display bin of green vegetables with a price sign", 104: "shop display bin of red apples with a price sign",
        105: "sacks of vegetables", 106: "shop counter with green bottles and red cans", "107-108": "refrigerated display counter with meat",
        109: "shop counter with stacked red cans", 110: "shop counter with blue and green goods", "111-112": "broken shop counter debris",
        113: "pyramid stack of blue cans", 114: "shop counter with blue cans", 115: "pyramid stack of orange cans",
    },
    "URBITS.PCK": {
        "0-1": "white wooden picket fence", "2-3": "broken white picket fence", "4-5": "black iron railing fence",
        "6-7": "broken black iron railing", "8-9": "brown wooden plank fence", "10-11": "broken brown wooden fence",
        "12-13": "trimmed green hedge", "14-15": "low green hedge", 16: "green grass lawn", 17: "brown dirt",
        18: "apple tree with red apples", 19: "grass with small blue and pink flowers", 20: "grass with yellow tulips",
        21: "dirt with green weeds", 22: "dark brown soil", 23: "grey metal dustbin", 24: "cardboard box of bottles",
    },
    "UFO1.PCK": {
        "0-1": "curved silver-grey alien hull segment with a purple floor edge", 2: "grey alien hull section with a door panel",
        "3-7": "dark grey curved alien hull segment with a blue rim", 8: "purple alien floor plate",
        "9-11": "dark alien floor with a purple centre", "12-16": "dark grey curved alien hull segment with a blue rim",
        17: "purple alien floor plate", 18: "curved dark alien hull with a purple floor edge", 19: "grey alien hull section with a door",
        20: "curved dark alien hull with a purple floor edge", 21: "dark grey alien dome roof", 22: "purple alien floor edge",
        "23-26": "grey alien landing leg strut",
    },
    "U_EXT02.PCK": {
        "0-1": "curved lavender-grey alien hull wall", "2-3": "alien hull wall with a glowing white light panel",
        4: "flat alien hull panel with two slits", 5: "alien hull panel with a glowing square light", "6-7": "curved pointed alien hull edge",
        8: "alien hull corner with two glowing panels", "9-10": "alien hull wall with a door frame", "11-12": "alien hull wall with a control panel and green lights",
        13: "flat alien hull panel with a screen", "14-15": "flat alien hull panel with alien symbols",
        "16-23": "curved alien hull segment with a purple inner floor edge", "24-25": "thin dark alien hull rail",
        "26-31": "lavender-grey alien hull roof plate", 32: "wrecked alien hull floor", "33-39": "wrecked lavender alien hull debris",
    },
    "U_WALL02.PCK": {
        0: "lavender alien interior wall with an embossed emblem", "1-2": "lavender alien wall with a sliding door opening", 3: "thin lavender wall post",
        4: "lavender alien interior wall with an embossed emblem", "5-6": "lavender alien wall with a sliding door opening", 7: "thin lavender wall post",
        "8-9": "lavender alien wall rubble", "10-11": "grey-blue alien wall with a control panel", 12: "small grey-blue wall panel", 13: "thin dark rail",
        "14-15": "grey-blue alien wall with panels", 16: "small grey-blue wall panel", 17: "thin dark rail", "18-19": "broken grey-blue alien wall frame",
        "20-21": "red glowing alien floor plate", "22-23": "barrier of vertical yellow energy beams", 24: "red debris on the floor",
        25: "purple glowing alien floor", 26: "purple rubble", "27-28": "light grey alien wall with a glowing square light",
        29: "grey alien wall pillar", "30-31": "light grey ribbed alien wall", 32: "grey alien pedestal", "33-34": "dark curved alien bench debris",
        35: "small grey stub", 36: "purple alien floor with a red glowing centre", "37-40": "blue alien chair with a rounded seat on a glowing base",
        "41-48": "alien console with a dark green data screen", "49-50": "alien console with a blue screen and keyboard",
        51: "round pink alien navigation machine", "52-53": "pink alien machine with dark blue glowing panels", 54: "pink alien device with blue circles",
        55: "wrecked alien console", 56: "wrecked pink alien machine", "57-58": "wrecked alien device with exposed blue circuits",
        59: "pink alien device with blue circles", 60: "dark blue debris", "61-64": "alien power source, orange glowing cylinder on a dark grey base",
        65: "destroyed power source, burnt crater",
    },
    "U_BITS.PCK": {
        "0-2": "grey alien landing leg strut", "3-7": "lavender alien hull plate with a raised pattern",
    },
    "U_DISEC2.PCK": {
        0: "white cylindrical tank of blue liquid", "1-3": "white cylindrical tank of blue liquid with organs inside",
        4: "shattered glass tank debris", 5: "dead alien specimen", "6-7": "dissection table with a yellow alien body",
        "8-9": "dissection table with a red carcass", 10: "dark organic debris", "11-14": "thin blue laboratory stand with a probe",
        15: "examination tray with red tissue", 16: "examination tray with red organs", 17: "blue floor grate with dark holes",
        "18-19": "alien examination chair with blue tubes", "20-21": "wrecked examination chair debris",
    },
    "U_OPER2.PCK": {
        "0-5": "alien surgical wall panel with blue and pink tubes", "6-7": "dark curved bench debris",
        "8-9": "pink alien operating table with a dotted top", 10: "pink alien operating table with a blue disc",
        11: "pink alien cabinet with dials", "12-14": "wrecked pink alien table debris",
    },
    "U_PODS.PCK": {
        "0-3": "red alien pod on blue legs", "4-6": "silver alien sphere with a pink lens on a stalk",
        "7-14": "alien tank of orange liquid with a lavender frame", "15-16": "shattered tank with spilled orange liquid",
        "17-24": "alien tank of blue liquid with a lavender frame", "25-26": "shattered tank with spilled blue liquid",
    },
    "U_BASE.PCK": {
        "0-8": "orange alien containment cage with a specimen inside", 9: "brown organic debris",
        "10-12": "alien vat with a yellow liquid tank", 13: "yellow alien storage cylinder with a brown frame",
        "14-17": "green glowing alien tank", "18-20": "blue alien tank with a yellow frame", 21: "brown alien cylinder with blue windows",
        "22-25": "pink alien tank with a brain inside", 26: "red and purple alien pod", "27-28": "orange alien cylinder with a purple band",
        29: "yellow glass alien cylinder", "30-33": "brown organic debris", "34-37": "red-brown alien coral with blue tips",
        "38-39": "orange trumpet-shaped alien fungus", "40-42": "purple alien egg sac", "43-46": "purple alien pot with a dark opening",
        47: "orange trumpet-shaped alien fungus", 48: "orange alien fungus", "49-50": "dark green alien plant with yellow flowers",
        "51-54": "green alien plant with broad leaves", "55-56": "dark rocky alien base wall with lavender edges",
        57: "dark rocky wall post", 58: "dark rocky alien floor", "59-60": "broken rocky wall debris", 61: "small rock",
        62: "dark rubble", 63: "brown earth block", 64: "brown earth floor", "65-66": "green glowing alien floor",
        67: "lavender alien floor plate with a raised pattern", 68: "lavender floor rubble", "69-70": "lavender alien doorway frame",
    },
    "XBASE1.PCK": {
        0: "brown earth floor", 1: "tall brown earth block", 2: "pink concrete wall with a maze relief and an earth top",
        3: "brown earth block with a white top edge", "4-5": "brown earth block edge with a white pillar", 6: "white glowing floor light panel",
        7: "pink-grey concrete floor", 8: "concrete floor with a burnt mark", "9-10": "white tiled floor", 11: "floor with grey rubble",
        "12-17": "pink concrete base wall panel with small blue lights", 18: "pink wall post", 19: "pink concrete wall with a maze relief",
        20: "pink pillar with a white top", "21-25": "broken pink concrete wall debris", 26: "pink concrete staircase",
        "27-28": "pink concrete staircase, upper flight", 29: "pink concrete staircase", "30-31": "broken staircase rubble",
        "32-39": "pink hangar wall with a round grey vent and red and yellow warning stripes", "40-41": "red debris",
        "42-49": "grey corrugated metal shutter wall", "50-51": "grey rubble debris", 52: "blue bunk bed with a wooden frame",
        53: "blue bunk bed with pillows", "54-55": "dark blue office chair", "56-57": "blue armchair", 58: "blue table",
        "59-60": "blue filing cabinet", 61: "computer terminal on a blue desk", "62-64": "dark debris",
        "65-66": "desk lamp with a yellow bulb on a grey stand", "67-68": "grey lamp with a shade", "69-70": "lab bench with a white top and blue dotted side",
        71: "lab bench with a purple microscope", "72-73": "dark debris", "74-76": "broken lab bench", 77: "workbench with red tools",
        78: "blue machine with a robotic claw arm", 79: "white console with an antenna", 80: "white rounded console with lights",
        "81-84": "dark grey machine block with blue dotted panels", "85-86": "pink robotic arm", 87: "wrecked dark table",
        88: "blue machine with a claw arm", "89-90": "wrecked white console", "91-94": "wrecked dark machine block",
        "95-96": "wrecked pink robotic arm", "97-98": "monitor screen on a stand with white lights",
        "99-102": "metal storage shelves with orange and pink shells", "103-104": "grey metal locker",
    },
    "XBASE2.PCK": {
        "0-8": "curved grey satellite dish segment", 9: "grey satellite dish on a pedestal", 10: "small grey dish on a pole",
        "11-12": "curved grey dish edge on a stand", 13: "grey machine with pink and blue cables", "14-15": "grey device with a white screen and blue cables",
        16: "wrecked grey machine with cables", "17-18": "wrecked grey device with cables", "19-20": "blue glowing wall panel",
        21: "blue tiled floor", "22-23": "broken blue panel debris", 24: "cracked blue floor", 25: "wooden barrel",
        "26-29": "grey-green metal floor plate with a white edge", 30: "grey rubble floor", "31-32": "grey metal cylinder tank",
        "33-36": "grey generator column with blue coils on a purple base", "37-40": "grey generator column with green bands on a purple base",
        "41-44": "purple reactor column with an orange glowing top", "45-46": "purple and grey curved machine part",
        47: "purple dome with a grey top", 48: "purple and grey curved machine part", "49-52": "purple machine base with a blue orb",
        "53-55": "dark wrecked machine debris", 56: "dark debris", "57-60": "dark purple grated floor", "61-62": "blue metal cylinder tank",
    },
    "PLANE.PCK": {
        "0-1": "aircraft landing gear with twin wheels", 2: "beige checkered cargo floor grate",
        "3-6": "lavender curved aircraft interior wall with red lights", 7: "dark grey wing edge with a red light",
        8: "dark grey aircraft hull panel", 9: "dark grey fuselage with a yellow X-COM roundel", "10-11": "dark grey curved fuselage",
        12: "small dark grey hull piece", 13: "dark grey wing tip with a red light", 14: "dark grey hull panel with an orange stripe",
        15: "grey loading ramp with red lights", "16-39": "dark grey aircraft wing surface with panel lines", 40: "grey wing tip",
        41: "grey fuselage with an orange stripe", "42-44": "open cargo hold with a dark interior and orange stripes",
        45: "aircraft cockpit nose with blue windows and a yellow panel", 46: "aircraft hull side with an engine intake",
        47: "dark grey tail fin", "48-51": "light grey wing segment", "52-53": "thin grey wing edge",
        "54-56": "beige checkered cargo floor with a lavender edge", 57: "cockpit with a blue canopy and yellow panel",
        "58-59": "lavender aircraft interior wall", "60-61": "grey loading ramp", 62: "beige floor plate",
    },
    "LIGHTNIN.PCK": {
        0: "beige hull wall with a blue screen", 1: "beige panel wall with yellow lights", 2: "beige wall with a control panel and buttons",
        3: "beige wall with yellow lights", 4: "thin beige post", "5-6": "grey machinery wall with an orange base line",
        "7-9": "grey machinery wall with pipes and yellow lights", 10: "grey machinery wall", 11: "thin grey post",
        "12-17": "beige wall with a green screen and pink buttons", "18-21": "grey machine pillar on a round base",
        "22-24": "grey seat on a brown pedestal", "25-29": "beige checkered floor plate", "30-31": "beige console with lights",
        32: "beige machine with a blue screen", 33: "beige floor with a step", 34: "grey ramp with rails", 35: "grey machine with yellow lights",
        36: "grey dish plate", "37-41": "grey hull top plate", 42: "grey ramp with pink rails", "43-46": "grey hull panel with a glowing red and yellow engine",
        47: "purple engine cone with blue lights", "48-50": "purple engine cone with an orange glowing cylinder",
    },
    "AVENGER.PCK": {
        "0-5": "grey ribbed hull ramp segment with a lavender edge", "6-7": "grey hull post with a lavender edge", 8: "grey hull top plate",
        9: "lavender inner wall edge", 10: "grey hull with an orange stripe", 11: "grey hull segment with a stairway",
        12: "grey hull panel with a maze relief", "13-16": "lavender inner wall piece", 17: "grey pointed hull fin", 18: "lavender block",
        19: "grey hull fin", 20: "purple egg-shaped engine pod", 21: "grey engine with a pink glowing exhaust",
        22: "grey engine block with a red exhaust", 23: "grey ribbed block", "24-25": "console with a blue screen",
        26: "grey machinery wall", 27: "purple egg-shaped engine pod", 28: "grey engine with a pink glowing exhaust", 29: "grey ribbed block",
        30: "grey engine block with two exhausts and blue lights", "31-32": "engine cylinder with a pink exhaust and blue lights",
        33: "grey hull with a glowing red and yellow roundel", "34-36": "grey hull panel with a maze relief", "37-43": "beige checkered floor plate",
        44: "purple seat on a pedestal", 45: "beige console wall with an orange bar", "46-49": "beige wall with a maze relief and lights",
        50: "grey block with beige maze walls", 51: "beige maze relief panel", "52-53": "purple robotic arm on a grey base",
        "54-60": "lavender curved bench", 61: "beige floor plate",
    },
    "MARS.PCK": {
        0: "orange martian sand", "1-3": "orange martian sand with dark cracks", 4: "martian sand with dark rocks",
        "5-7": "orange martian boulder", "8-9": "martian sand with a dark crater", "10-21": "orange martian rock outcrop",
        22: "orange martian rock slope", 23: "tall orange rock block", "24-31": "orange martian rock slope", 32: "orange rock block",
        "33-34": "green glowing alien floor", "35-36": "lavender alien doorway frame",
    },
    "BRAIN.PCK": {
        "0-7": "giant alien brain in a grey shell with a green membrane and a dark eye",
    },
}


def hints_for(set_name):
    """The hints of a set as {frame index: text}, ranges expanded."""
    out = {}
    for key, text in HINTS.get(set_name.upper(), {}).items():
        if isinstance(key, str) and "-" in key:
            a, b = key.split("-")
            for i in range(int(a), int(b) + 1):
                out[i] = text
        else:
            out[int(key)] = text
    return out
