<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
    <RootNamespace>Xp.Launcher.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Xp.Manifest\Xp.Manifest.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Xp.Launcher.Core.Tests" />
  </ItemGroup>
</Project>
