name: Build Global Transfers patched OXCE

on:
  workflow_dispatch:

jobs:
  windows:
    name: Windows x86 XP-compatible
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Apply Global Transfers patch
        shell: powershell
        run: python tools/apply_global_transfers_patch.py

      - name: Setup environment
        shell: bash
        run: |
          echo "DATEFILE=`git log -1 --date=format:\"%Y_%m_%d_%H%M\" --format=\"%ad\"`" >> $GITHUB_ENV
          echo "DATEVERSION=`git log -1 --date=format:\"%Y-%m-%d %H:%M\" --format=\"%ad\"`" >> $GITHUB_ENV

      - name: Setup version info
        shell: bash
        run: |
          sed -i "s/GAME_VERSION_GIT \"[^\"]*\"/GAME_VERSION_GIT \" git ${{ env.DATEVERSION }} global-transfers\"/" install/win/version.nsh
          sed -i "s/GAME_DATE_GIT \"[^\"]*\"/GAME_DATE_GIT \"${{ env.DATEFILE }}\"/" install/win/version.nsh
          sed -i "s/OPENXCOM_VERSION_GIT \"[^\"]*\"/OPENXCOM_VERSION_GIT \" git ${{ env.DATEVERSION }} global-transfers\"/" src/version.h
          echo "FILENAME=oxce_global_transfers_${{ env.DATEFILE }}" >> $GITHUB_ENV

      - name: Install XP Toolset
        shell: powershell
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $WorkLoads = '--add Microsoft.VisualStudio.Component.WinXP'
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"", $WorkLoads, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          if ($process.ExitCode -eq 0) { Write-Host "components have been successfully added" } else { Write-Host "components were not installed" }

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Compile source x86
        env:
          VC_FLAGS: /v:minimal /m /p:BuildInParallel=true /p:PreferredToolArchitecture=x64 /p:Configuration=Release_XP
        shell: powershell
        run: |
          cd src
          msbuild OpenXcom.2010.sln $env:VC_FLAGS /p:Platform=Win32
          cd ..
          Rename-Item -Path "bin\Win32\Release_XP" -NewName "Release"

      - name: Create ZIP
        shell: powershell
        run: |
          New-Item -ItemType "directory" -Path "artifacts"
          Compress-Archive -Path "bin\Win32\Release\OpenXcom.exe", "bin\Win32\*.dll", "bin\common", "bin\standard", "bin\TFTD", "bin\UFO", "LICENSE.txt" -DestinationPath "artifacts\${{ env.FILENAME }}_win32_xp.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: oxce_global_transfers_windows
          path: artifacts/*
